/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class UniffiNativeModule {
  static open(path: string): UniffiNativeModule
  register(definitions: object): object
}
